blank_issues_enabled: false
contact_links:
  - name: Search existing issues
    url: https://github.com/denislirette/baseballscorebook/issues
    about: Please check if your issue already exists before creating a new one.
